name: Workflow Coordinator
run-name: ${{ github.event.number }} - ${{ github.ref }} - "${{ github.sha }}"
on: push

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Clone & Checkout
        uses: actions/checkout@v5
        with:
          token: FIXME
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.12.2" # TODO; ensure ok
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Clone & Checkout
        uses: actions/checkout@v5
        with:
          token: FIXME
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.12.2" # TODO; ensure ok
#      - name: Get AWS credentials
#        # TODO: this
#        # TODO: backend bucket
#      - run: terraform init -backend-config='bucket=${{ inputs.account_name }}-${{ inputs.environment }}-${{ inputs.terraform_bucket_suffix }}'
#      - run: terraform plan -var-file=production.tfvars -out=plan.tf
#      - run: terraform apply -auto-approve plan.tf